# fly.toml app configuration file generated for telegraf on 2023-05-30T10:23:20+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "filcdn-telegraf"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true
